[application]
name = "pks_website"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Skullhouse | MIT"

[web.watcher]
watch_path = ["src", "public"]
reload_html = true
index_on_404 = true

[web.resource]
style = [
    "./style/index.css"
]

[web.resource.dev]